inventory:
  url: http://65.2.73.67:8082

spring:
  datasource:
    url: jdbc:mysql://database-1.cluster-ct66kgqog8ty.ap-south-1.rds.amazonaws.com:3306/coffee_shop?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC # Replace <your_database_name>
    username: admin # Replace
    password: admin123 # Replace
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # Or none for production
    show-sql: true # Optional
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
